### ISSUE TITLE
Preferences in Context Menu?

### ISSUE THREAD

**Issue by stevenvachon** [hoyois/safariextensions#1]
I honestly do not like the idea of lengthening my context menu. I like things really simple and since I'll rarely ever be opening the ClickToFlash Preferences panel, I think it'd be best kept within the Safari Extensions tab/window.

**Comment by hoyois** [comment]
You can make the context menu item disappear with this command:

defaults write com.apple.Safari ExtensionSettings-com.hoyois.safari.clicktoflash-GY5KR7239Q -dict-add settingsContext -string 'false'

**Comment by stevenvachon** [comment]
Thank you. However, then I cannot access the preferences panel at all, without first re-enabling the context menu item.

Perhaps consider putting this menu item back in the Safari menu?

**Comment by hoyois** [comment]
Extensions can't modify the menus in the menubar.
If you disable this menu item you should remember the keyboard shortcut that opens the preference pane (the last one in the keyboard shortcut section).
