### ISSUE TITLE
Could Click to Flash available on Chrome as well? 

### ISSUE THREAD

**Issue by inew** [hoyois/safariextensions#2]
Well,I love "Click to flash" on safari so much,however when i back using chrome on my mac,i can't find it on chrome web store,i know chrome is not  support H.264,but i really love click to flash!!

Could you develop CTF on Chrome as well ? Maybe it use Webm?

Thank you so much!

**Comment by hoyois** [comment]
That's too much work for me, but the source code is freely available, so anyone is welcome to port it.

Marc
