### ISSUE TITLE
ClickToFlash 2.2.6 doesn't work in Safari 5.1 beta

### ISSUE THREAD

**Issue by amw** [hoyois/safariextensions#3]
Hi,

Last week I've upgraded Safari to 5.1 beta. Click to flash was working correctly like it used to before browser upgrade. Today I've updated the extension to 2.2.6 (unfortunately I don't remember my previous version) and now I get flash everywhere. Extension is enabled, I can access preferences from context menu. It's just that it doesn't block anything.

Let me know what details you might find helpful and I'll provide you with them.

Cheers

**Comment by amw** [comment]
I have reverted the extension to the previous version 2.1.4 using a copy on my other computer and it works fine again.

**Comment by hoyois** [comment]
I use Safari 5.1 and everything works fine. Try uninstalling before installing 2.2.6.

Marc
