### ISSUE TITLE
Placeholders should have hover and click states

### ISSUE THREAD

**Issue by Examinus** [hoyois/safariextensions#5]
Would it be possible to give placeholders a hover and active states (when you click down).

Not having these makes the extension feel a little unresponsive.

**Comment by hoyois** [comment]
They do have "click states" already. It's a matter of taste, but I think most users including myself would rather not have hover states.

**Comment by hoyois** [comment]
You can easily customize any extension's CSS, by the way, so you can design your own hover states.

For example, you can add something like

.CTPplaceholder.CTPnoimage .CTPplaceholderContainer:hover {
    opacity: 1 !important;
}

in a user stylesheet (in Safari > Preferences > Advanced).
