### ISSUE TITLE
AdBlock ClickToFlash compatibility mode

### ISSUE THREAD

**Issue by Neelfyn** [hoyois/safariextensions#8]
Hey,

I'm Neelfyn from the AdBlock team.

We've had several requests from users who wanted to use ClickToFlash's YouTube killer and AdBlock at the same time. If Flash wasn't installed, the normal YouTube player would load.

Yesterday we released AdBlock version 2.17, which has an option at **AdBlock button > Options > General > Enable ClickToFlash compatibility mode** to prevent this issue. When this is enabled, AdBlock simply doesn't mess with the player, which it would normally do to block ads, but this is obviously not needed when the YouTube killer is in use.

Thought you might want to update your [help section](https://github.com/hoyois/safariextensions/blob/gh-pages/clicktoplugin/help.xhtml#L71) with this. :)

**Comment by hoyois** [comment]
Thanks, this is really appreciated! I will update the web page soon.

**Comment by Fofer** [comment]
Nice!  Thanks to you and your team for adding this, Neelfyn.
